const API=(window.API_BASE||"").replace(/\/$/,"");const $=s=>document.querySelector(s);const money=n=>"৳"+Number(n||0).toLocaleString("en-BD");let products=[],settings={},agents=[],cart=JSON.parse(localStorage.getItem("fm_cart")||"[]"),category="All";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function api(path,opt){const r=await fetch(API+path,opt);const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||"Request failed");return j}
function save(){localStorage.setItem("fm_cart",JSON.stringify(cart));renderCart();$("#cartCount").textContent=cart.reduce((a,x)=>a+x.qty,0)}
function toast(t){const x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2300)}
function renderCategories(){const cats=["All",...new Set(products.map(p=>p.category).filter(Boolean))];$("#categoryChips").innerHTML=cats.map(c=>`<button class="chip ${c===category?"active":""}" onclick="setCategory('${esc(c)}')">${esc(c)}</button>`).join("")}
window.setCategory=c=>{category=c;renderCategories();renderProducts()}
function filtered(){let q=$("#search").value.trim().toLowerCase(),a=products.filter(p=>(category==="All"||p.category===category)&&(!q||`${p.name} ${p.description} ${p.category} ${p.tags||""}`.toLowerCase().includes(q)));const s=$("#sort").value;if(s==="priceLow")a.sort((x,y)=>x.price-y.price);if(s==="priceHigh")a.sort((x,y)=>y.price-x.price);if(s==="name")a.sort((x,y)=>x.name.localeCompare(y.name));return a}
function renderProducts(){const a=filtered();$("#products").innerHTML=a.length?a.map(p=>`<article class="card-product"><div class="pimg"><img src="${esc(p.image||"assets/product-placeholder.jpg")}" alt="${esc(p.name)}" loading="lazy"><span class="badge">${p.discount_percent?`-${p.discount_percent}%`:(p.is_new?"NEW":"FM")}</span><button class="heart" onclick="toggleWish(${p.id})">♡</button></div><div class="pbody"><h3>${esc(p.name)}</h3><div class="rating">★ ${Number(p.rating||5).toFixed(1)} · ${Number(p.review_count||0)} reviews</div><div class="price">${money(p.price)} ${p.old_price?`<span class="old">${money(p.old_price)}</span>`:""}</div><div class="pactions"><button onclick="add(${p.id})">🛒 Add to Cart</button><button class="buy" onclick="buy(${p.id})">⚡ Buy Now</button></div></div></article>`).join(""):`<div class="empty" style="grid-column:1/-1">কোনো product পাওয়া যায়নি।</div>`}
function add(id){const x=cart.find(i=>i.id===id);if(x)x.qty++;else cart.push({id,qty:1});save();toast("Cart-এ যোগ হয়েছে ✓")}
function buy(id){add(id);openCheckout()}
window.add=add;window.buy=buy;window.toggleWish=id=>toast("Wishlist feature প্রস্তুত আছে—login system connect করলে account-এ save হবে।");
function renderCart(){const rows=cart.map(x=>{const p=products.find(y=>y.id===x.id);if(!p)return"";return `<div class="cart-row"><img src="${esc(p.image)}"><div style="flex:1"><b>${esc(p.name)}</b><div>${money(p.price)}</div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button>${x.qty}<button onclick="changeQty(${p.id},1)">+</button><button onclick="removeCart(${p.id})">Remove</button></div></div></div>`}).join("");$("#cartItems").innerHTML=rows||'<div class="empty">Cart empty</div>';const total=cart.reduce((s,x)=>{const p=products.find(y=>y.id===x.id);return s+(p?p.price*x.qty:0)},0);$("#cartTotal").textContent=money(total)}
window.changeQty=(id,n)=>{const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=n;if(x.qty<1)cart=cart.filter(i=>i.id!==id);save()};window.removeCart=id=>{cart=cart.filter(i=>i.id!==id);save()};
function openOverlay(id){$(id).classList.add("open")}function closeOverlays(){document.querySelectorAll(".overlay").forEach(x=>x.classList.remove("open"))}
$("#cartBtn").onclick=()=>openOverlay("#drawer");document.querySelectorAll("[data-close]").forEach(b=>b.onclick=closeOverlays);$("#menuBtn").onclick=()=>$("#mobileNav").classList.toggle("open");$("#sort").onchange=renderProducts;$("#search").oninput=renderProducts;$("#searchBtn").onclick=renderProducts;
function openCheckout(){if(!cart.length)return toast("আগে product নির্বাচন করুন");$("#drawer").classList.remove("open");const total=cart.reduce((s,x)=>{const p=products.find(y=>y.id===x.id);return s+(p?p.price*x.qty:0)},0);$("#checkoutSummary").innerHTML=`<div class="summary"><span>${cart.length} item</span><b>${money(total)}</b></div>`;$("#payments").innerHTML=Object.entries(settings.payment_methods||{}).filter(([k,v])=>v.enabled).map(([k,v],i)=>`<label class="pay-option"><span><b>${esc(k)}</b><small>${esc(v.number||"")}</small></span><input type="radio" name="payment_method" value="${esc(k)}" ${i===0?"checked":""}></label>`).join("")||'<p class="muted">Payment method unavailable. Please contact agent.</p>';openOverlay("#checkoutModal")}
$("#checkout").onclick=openCheckout;
$("#checkoutForm").onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.items=cart;try{const j=await api("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});cart=[];save();e.target.hidden=true;$("#success").hidden=false;$("#success").innerHTML=`<b>Order successful 🎉</b><br>Order ID: <b>${esc(j.orderId)}</b><br>Total: <b>${money(j.total)}</b><br><small>এই Order ID রেখে tracking-এর জন্য ব্যবহার করুন।</small>`}catch(x){toast(x.message)}};
function renderAgents(){const html=agents.length?agents.map(a=>`<div class="agent"><div><b>${esc(a.name)}</b><small>Support Agent</small></div><a href="${esc(a.whatsapp_url||"#")}" target="_blank" rel="noopener">WhatsApp ↗</a></div>`).join(""):'<div class="empty">এখন কোনো active agent নেই।</div>';$("#agents").innerHTML=html;$("#agentModalList").innerHTML=agents.map(a=>`<div class="agent" style="margin:8px 0"><div><b>${esc(a.name)}</b></div><div style="display:flex;gap:6px">${a.whatsapp_url?`<a href="${esc(a.whatsapp_url)}" target="_blank" class="btn gold">WhatsApp</a>`:""}${a.messenger_url?`<a href="${esc(a.messenger_url)}" target="_blank" class="btn ghost">Messenger</a>`:""}</div></div>`).join("")||'<p class="muted">No active agent.</p>'}
$("#agentFab").onclick=()=>openOverlay("#agentModal");$("#aiFab").onclick=()=>{$("#chat").classList.add("open");$("#chatInput").focus()};$("#heroChat").onclick=()=>{$("#chat").classList.add("open");$("#chatInput").focus()};$("#chatClose").onclick=()=>$("#chat").classList.remove("open");
function bubble(t,type){const d=document.createElement("div");d.className=`bubble ${type}`;d.textContent=t;$("#messages").append(d);$("#messages").scrollTop=99999}
$("#chatForm").onsubmit=async e=>{e.preventDefault();const q=$("#chatInput").value.trim();if(!q)return;bubble(q,"user");$("#chatInput").value="";bubble("ভাবছি…","bot");try{const j=await api("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:q})});$("#messages").lastElementChild.remove();bubble(j.reply||"দুঃখিত, এখন উত্তর দিতে পারছি না।","bot")}catch{toast("AI service unavailable")}};
async function load(){try{[products,settings,agents]=await Promise.all([api("/api/products"),api("/api/settings"),api("/api/agents")]);$("#logo").src=settings.logo||"assets/logo.png";document.title=`${settings.store_name||"FM FASHION"} — Premium Store`;renderCategories();renderProducts();renderAgents();save();const pm=settings.payment_methods||{};$("#footerPay").textContent=Object.entries(pm).filter(([,v])=>v.enabled).map(([k,v])=>`${k}${v.number?" · "+v.number:""}`).join(" · ")||"Contact Agent";}catch(e){$("#products").innerHTML='<div class="empty" style="grid-column:1/-1">API connect হয়নি। config.js-এ আপনার API URL বসান।</div>';console.error(e)}}
load();
