const API=(window.API_BASE||"").replace(/\/$/,"");
const $=s=>document.querySelector(s);
const money=n=>"৳"+Number(n||0).toLocaleString("en-BD");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
let state={products:[],orders:[],agents:[],settings:{}};
async function api(path,opt={}){opt.credentials="include";const r=await fetch(API+path,opt);const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`Request failed (${r.status})`);return j}
function toast(msg){let el=document.getElementById("adminToast");if(!el){el=document.createElement("div");el.id="adminToast";el.style.cssText="position:fixed;right:18px;bottom:18px;z-index:9999;background:#111;color:#fff;padding:12px 16px;border-radius:12px;box-shadow:0 10px 30px #0004";document.body.appendChild(el)}el.textContent=msg;el.hidden=false;clearTimeout(el._t);el._t=setTimeout(()=>el.hidden=true,2500)}
function formDataObject(form){return Object.fromEntries(new FormData(form));}
function setupTabs(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".panel").forEach(x=>x.classList.toggle("active",x.id===b.dataset.tab));});}
async function login(e){e.preventDefault();const password=$("#password").value;try{await api("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});$("#login").hidden=true;$("#app").hidden=false;await loadAll();toast("Login successful");}catch(err){$("#loginError").textContent=err.message;}}
async function logout(){try{await api("/api/admin/logout",{method:"POST"})}catch{}location.reload()}
function renderProducts(){
 $("#productTable").innerHTML=state.products.length?`<div class="table-wrap"><table><thead><tr><th>Product</th><th>Price</th><th>Category</th><th>Flags</th><th>Action</th></tr></thead><tbody>${state.products.map(p=>`<tr><td><div style="display:flex;gap:10px;align-items:center"><img src="${esc(imageUrl(p.image))}" style="width:52px;height:52px;object-fit:cover;border-radius:10px"><div><b>${esc(p.name)}</b><small style="display:block">#${p.id}</small></div></div></td><td>${money(p.price)} ${p.old_price?`<del>${money(p.old_price)}</del>`:""}</td><td>${esc(p.category||"General")}</td><td>${p.featured?"Featured ":""}${p.is_new?"New":""}</td><td><button onclick="editProduct(${p.id})">Edit</button> <button onclick="deleteProduct(${p.id})">Delete</button></td></tr>`).join("")}</tbody></table></div>`:`<div class="empty">No products yet. Add your first product.</div>`;
}
function imageUrl(src){if(!src)return "assets/logo.png";return src.startsWith("http")?src:(src.startsWith("/")?API+src:src);}
window.editProduct=id=>{const p=state.products.find(x=>x.id===id);if(!p)return;const f=$("#productForm");f.reset();for(const k of ["id","name","price","old_price","category","description","tags"])if(f.elements[k])f.elements[k].value=p[k]??"";f.elements.featured.checked=!!p.featured;f.elements.is_new.checked=!!p.is_new;$("#pTitle").textContent="Edit Product";$("#productModal").classList.add("open")};
window.deleteProduct=async id=>{if(!confirm("Delete this product?"))return;try{await api(`/api/admin/products/${id}`,{method:"DELETE"});await loadAll();toast("Product deleted")}catch(e){toast(e.message)}};
async function saveProduct(e){e.preventDefault();const f=e.target;const data=new FormData(f);const id=data.get("id");try{await api(id?`/api/admin/products/${id}`:"/api/admin/products",{method:id?"PUT":"POST",body:data});$("#productModal").classList.remove("open");f.reset();await loadAll();toast("Product saved and synced to store")}catch(e){toast(e.message)}}
function renderOrders(){ $("#orderTable").innerHTML=state.orders.length?`<div class="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th></tr></thead><tbody>${state.orders.map(o=>`<tr><td>FMF-${String(o.id).padStart(6,"0")}</td><td>${esc(o.customer_name)}<small style="display:block">${esc(o.phone)}</small></td><td>${money(o.total)}</td><td>${esc(o.payment_method)}</td><td><select onchange="updateOrder(${o.id},this.value)">${["Pending","Confirmed","Processing","Shipped","Delivered","Cancelled"].map(s=>`<option ${s===o.status?"selected":""}>${s}</option>`).join("")}</select></td></tr>`).join("")}</tbody></table></div>`:`<div class="empty">No orders yet.</div>`}
window.updateOrder=async(id,status)=>{try{await api(`/api/admin/orders/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});toast("Order status updated")}catch(e){toast(e.message)}};
function renderAgents(){ $("#agentTable").innerHTML=state.agents.length?`<div class="table-wrap"><table><thead><tr><th>Agent</th><th>WhatsApp</th><th>Messenger</th><th>Active</th><th>Action</th></tr></thead><tbody>${state.agents.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.whatsapp)}</td><td>${a.messenger_url?`<a href="${esc(a.messenger_url)}" target="_blank">Open</a>`:"—"}</td><td>${a.active?"Yes":"No"}</td><td><button onclick="editAgent(${a.id})">Edit</button> <button onclick="deleteAgent(${a.id})">Delete</button></td></tr>`).join("")}</tbody></table></div>`:`<div class="empty">No agents yet.</div>`}
window.editAgent=id=>{const a=state.agents.find(x=>x.id===id);if(!a)return;const f=$("#agentForm");f.reset();f.elements.id.value=a.id;f.elements.name.value=a.name;f.elements.whatsapp.value=a.whatsapp;f.elements.messenger_url.value=a.messenger_url||"";f.elements.active.checked=!!a.active;$("#agentModal").classList.add("open")};
window.deleteAgent=async id=>{if(!confirm("Delete this agent?"))return;try{await api(`/api/admin/agents/${id}`,{method:"DELETE"});await loadAll();toast("Agent deleted") }catch(e){toast(e.message)}};
async function saveAgent(e){e.preventDefault();const f=e.target,d=new URLSearchParams(new FormData(f));const id=d.get("id");try{await api(id?`/api/admin/agents/${id}`:"/api/admin/agents",{method:id?"PUT":"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:d});$("#agentModal").classList.remove("open");f.reset();await loadAll();toast("Agent saved and synced to store")}catch(e){toast(e.message)}}
function fillSettings(){const s=state.settings,f=$("#settingsForm");f.elements.store_name.value=s.store_name||"FM FASHION";f.elements.logo.value=s.logo||"";f.elements.delivery_promise.value=s.delivery_promise||"";f.elements.bkash_number.value=s.bkash_number||"";f.elements.nagad_number.value=s.nagad_number||"";f.elements.rocket_number.value=s.rocket_number||"";f.elements.bkash_enabled.checked=s.bkash_enabled==="1";f.elements.nagad_enabled.checked=s.nagad_enabled==="1";f.elements.rocket_enabled.checked=s.rocket_enabled==="1";f.elements.cod_enabled.checked=s.cod_enabled==="1";f.elements.payment_note.value=s.payment_note||"";$("#storeTitle").textContent=s.store_name||"FM FASHION";}
async function saveSettings(e){e.preventDefault();const f=e.target,d=formDataObject(f);for(const k of ["bkash_enabled","nagad_enabled","rocket_enabled","cod_enabled"])d[k]=f.elements[k].checked?"1":"0";try{const j=await api("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});state.settings=j.settings;fillSettings();$("#saved").textContent="✓ Saved";toast("Payment & store settings synced")}catch(e){toast(e.message)}}
function addSecurity(){const panel=$("#settings");if(panel.querySelector("#passwordChangeForm"))return;const box=document.createElement("div");box.className="form";box.style.marginTop="28px";box.innerHTML=`<h2>Admin Security</h2><form id="passwordChangeForm" class="form"><label>Current password<input name="current_password" type="password" required></label><label>New password<input name="new_password" type="password" minlength="6" required></label><label>Confirm new password<input name="confirm_password" type="password" minlength="6" required></label><button class="gold">Change Admin Password</button><span id="passwordSaved"></span></form>`;panel.appendChild(box);$("#passwordChangeForm").onsubmit=async e=>{e.preventDefault();const d=formDataObject(e.target);if(d.new_password!==d.confirm_password)return toast("New passwords do not match");try{await api("/api/admin/password",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({current_password:d.current_password,new_password:d.new_password})});e.target.reset();$("#passwordSaved").textContent="✓ Password changed";toast("Admin password changed")}catch(err){toast(err.message)}}}
async function runAI(e){e.preventDefault();const d=new FormData(e.target);try{const j=await api("/api/admin/ai-product",{method:"POST",body:d});const p=j.preview;$("#aiResult").innerHTML=`<div class="modal" style="margin-top:18px"><h3>AI Preview</h3><img src="${esc(imageUrl(p.image))}" style="width:180px;max-width:100%;border-radius:14px"><p><b>${esc(p.name)}</b></p><p>${esc(p.description)}</p><p>Category: ${esc(p.category)} · Tags: ${esc(p.tags)} · Price: ${money(p.price)}</p><button class="gold" id="publishAI">Publish Product</button></div>`;$("#publishAI").onclick=async()=>{const fd=new FormData();fd.append("name",p.name);fd.append("price",p.price);fd.append("category",p.category);fd.append("description",p.description);fd.append("tags",p.tags);fd.append("image_url",p.image);await api("/api/admin/products",{method:"POST",body:fd});$("#aiResult").innerHTML="<p>✓ Published</p>";await loadAll()}}catch(err){toast(err.message)}}
async function loadAll(){const [d,products,orders,agents,settings]=await Promise.all([api("/api/admin/dashboard"),api("/api/admin/products"),api("/api/admin/orders"),api("/api/admin/agents"),api("/api/admin/settings")]);state={products,orders,agents,settings};$("#revenue").textContent=money(d.revenue);$("#ordersCount").textContent=d.orders;$("#productsCount").textContent=d.products;$("#agentsCount").textContent=d.agents;renderProducts();renderOrders();renderAgents();fillSettings();addSecurity();}
async function init(){setupTabs();$("#storeLink").href=(API?API:"/");$("#loginForm").onsubmit=login;$("#logout").onclick=logout;$("#refresh").onclick=()=>loadAll().catch(e=>toast(e.message));$("#newProduct").onclick=()=>{$("#productForm").reset();$("#productForm").elements.id.value="";$("#pTitle").textContent="Add Product";$("#productModal").classList.add("open")};$("#newAgent").onclick=()=>{$("#agentForm").reset();$("#agentForm").elements.id.value="";$("#agentForm").elements.active.checked=true;$("#agentModal").classList.add("open")};$("#productForm").onsubmit=saveProduct;$("#agentForm").onsubmit=saveAgent;$("#settingsForm").onsubmit=saveSettings;$("#aiForm").onsubmit=runAI;document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest(".overlay").classList.remove("open"));try{await api("/api/admin/me");$("#login").hidden=true;$("#app").hidden=false;await loadAll()}catch{}}
init();
                                                                                                                                   
